defmodule CDPotion.Domain.Input do
  use CDPotion.Utils

  @doc """
  Dispatches a drag event into the page.
  ## Parameters:
    - `type:string`: Type of the drag event.
    - `x:number`: X coordinate of the event relative to the main frame's viewport in CSS pixels.
    - `y:number`: Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
  the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
    - `data:DragData`: description not provided :(
    - `modifiers:integer`: (Optional) Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
  (default: 0).
  """
  def dispatch_drag_event(type, x, y, data, modifiers \\ nil) do
    params =
      as_query([{"type", type}, {"x", x}, {"y", y}, {"data", data}, {"modifiers", modifiers}])

    {"Input.dispatchDragEvent", params}
  end

  @doc """
  Dispatches a key event to the page.
  ## Parameters:
    - `type:string`: Type of the key event.
    - `modifiers:integer`: (Optional) Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
  (default: 0).
    - `timestamp:TimeSinceEpoch`: (Optional) Time at which the event occurred.
    - `text:string`: (Optional) Text as generated by processing a virtual key code with a keyboard layout. Not needed for
  for `keyUp` and `rawKeyDown` events (default: "")
    - `unmodifiedText:string`: (Optional) Text that would have been generated by the keyboard if no modifiers were pressed (except for
  shift). Useful for shortcut (accelerator) key handling (default: "").
    - `keyIdentifier:string`: (Optional) Unique key identifier (e.g., 'U+0041') (default: "").
    - `code:string`: (Optional) Unique DOM defined string value for each physical key (e.g., 'KeyA') (default: "").
    - `key:string`: (Optional) Unique DOM defined string value describing the meaning of the key in the context of active
  modifiers, keyboard layout, etc (e.g., 'AltGr') (default: "").
    - `windowsVirtualKeyCode:integer`: (Optional) Windows virtual key code (default: 0).
    - `nativeVirtualKeyCode:integer`: (Optional) Native virtual key code (default: 0).
    - `autoRepeat:boolean`: (Optional) Whether the event was generated from auto repeat (default: false).
    - `isKeypad:boolean`: (Optional) Whether the event was generated from the keypad (default: false).
    - `isSystemKey:boolean`: (Optional) Whether the event was a system key event (default: false).
    - `location:integer`: (Optional) Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right (default:
  0).
    - `commands:array`: (Optional) Editing commands to send with the key event (e.g., 'selectAll') (default: []).
  These are related to but not equal the command names used in `document.execCommand` and NSStandardKeyBindingResponding.
  See https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/editor_command_names.h for valid command names.
  """
  def dispatch_key_event(
        type,
        modifiers \\ nil,
        timestamp \\ nil,
        text \\ nil,
        unmodified_text \\ nil,
        key_identifier \\ nil,
        code \\ nil,
        key \\ nil,
        windows_virtual_key_code \\ nil,
        native_virtual_key_code \\ nil,
        auto_repeat \\ nil,
        is_keypad \\ nil,
        is_system_key \\ nil,
        location \\ nil,
        commands \\ nil
      ) do
    params =
      as_query([
        {"type", type},
        {"modifiers", modifiers},
        {"timestamp", timestamp},
        {"text", text},
        {"unmodifiedText", unmodified_text},
        {"keyIdentifier", key_identifier},
        {"code", code},
        {"key", key},
        {"windowsVirtualKeyCode", windows_virtual_key_code},
        {"nativeVirtualKeyCode", native_virtual_key_code},
        {"autoRepeat", auto_repeat},
        {"isKeypad", is_keypad},
        {"isSystemKey", is_system_key},
        {"location", location},
        {"commands", commands}
      ])

    {"Input.dispatchKeyEvent", params}
  end

  @doc """
  This method emulates inserting text that doesn't come from a key press,
  for example an emoji keyboard or an IME.
  ## Parameters:
    - `text:string`: The text to insert.
  """
  def insert_text(text) do
    params = as_query([{"text", text}])
    {"Input.insertText", params}
  end

  @doc """
  This method sets the current candidate text for ime.
  Use imeCommitComposition to commit the final text.
  Use imeSetComposition with empty string as text to cancel composition.
  ## Parameters:
    - `text:string`: The text to insert
    - `selectionStart:integer`: selection start
    - `selectionEnd:integer`: selection end
    - `replacementStart:integer`: (Optional) replacement start
    - `replacementEnd:integer`: (Optional) replacement end
  """
  def ime_set_composition(
        text,
        selection_start,
        selection_end,
        replacement_start \\ nil,
        replacement_end \\ nil
      ) do
    params =
      as_query([
        {"text", text},
        {"selectionStart", selection_start},
        {"selectionEnd", selection_end},
        {"replacementStart", replacement_start},
        {"replacementEnd", replacement_end}
      ])

    {"Input.imeSetComposition", params}
  end

  @doc """
  Dispatches a mouse event to the page.
  ## Parameters:
    - `type:string`: Type of the mouse event.
    - `x:number`: X coordinate of the event relative to the main frame's viewport in CSS pixels.
    - `y:number`: Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
  the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
    - `modifiers:integer`: (Optional) Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
  (default: 0).
    - `timestamp:TimeSinceEpoch`: (Optional) Time at which the event occurred.
    - `button:MouseButton`: (Optional) Mouse button (default: "none").
    - `buttons:integer`: (Optional) A number indicating which buttons are pressed on the mouse when a mouse event is triggered.
  Left=1, Right=2, Middle=4, Back=8, Forward=16, None=0.
    - `clickCount:integer`: (Optional) Number of times the mouse button was clicked (default: 0).
    - `force:number`: (Optional) The normalized pressure, which has a range of [0,1] (default: 0).
    - `tangentialPressure:number`: (Optional) The normalized tangential pressure, which has a range of [-1,1] (default: 0).
    - `tiltX:integer`: (Optional) The plane angle between the Y-Z plane and the plane containing both the stylus axis and the Y axis, in degrees of the range [-90,90], a positive tiltX is to the right (default: 0).
    - `tiltY:integer`: (Optional) The plane angle between the X-Z plane and the plane containing both the stylus axis and the X axis, in degrees of the range [-90,90], a positive tiltY is towards the user (default: 0).
    - `twist:integer`: (Optional) The clockwise rotation of a pen stylus around its own major axis, in degrees in the range [0,359] (default: 0).
    - `deltaX:number`: (Optional) X delta in CSS pixels for mouse wheel event (default: 0).
    - `deltaY:number`: (Optional) Y delta in CSS pixels for mouse wheel event (default: 0).
    - `pointerType:string`: (Optional) Pointer type (default: "mouse").
  """
  def dispatch_mouse_event(
        type,
        x,
        y,
        modifiers \\ nil,
        timestamp \\ nil,
        button \\ nil,
        buttons \\ nil,
        click_count \\ nil,
        force \\ nil,
        tangential_pressure \\ nil,
        tilt_x \\ nil,
        tilt_y \\ nil,
        twist \\ nil,
        delta_x \\ nil,
        delta_y \\ nil,
        pointer_type \\ nil
      ) do
    params =
      as_query([
        {"type", type},
        {"x", x},
        {"y", y},
        {"modifiers", modifiers},
        {"timestamp", timestamp},
        {"button", button},
        {"buttons", buttons},
        {"clickCount", click_count},
        {"force", force},
        {"tangentialPressure", tangential_pressure},
        {"tiltX", tilt_x},
        {"tiltY", tilt_y},
        {"twist", twist},
        {"deltaX", delta_x},
        {"deltaY", delta_y},
        {"pointerType", pointer_type}
      ])

    {"Input.dispatchMouseEvent", params}
  end

  @doc """
  Dispatches a touch event to the page.
  ## Parameters:
    - `type:string`: Type of the touch event. TouchEnd and TouchCancel must not contain any touch points, while
  TouchStart and TouchMove must contains at least one.
    - `touchPoints:array`: Active touch points on the touch device. One event per any changed point (compared to
  previous touch event in a sequence) is generated, emulating pressing/moving/releasing points
  one by one.
    - `modifiers:integer`: (Optional) Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
  (default: 0).
    - `timestamp:TimeSinceEpoch`: (Optional) Time at which the event occurred.
  """
  def dispatch_touch_event(type, touch_points, modifiers \\ nil, timestamp \\ nil) do
    params =
      as_query([
        {"type", type},
        {"touchPoints", touch_points},
        {"modifiers", modifiers},
        {"timestamp", timestamp}
      ])

    {"Input.dispatchTouchEvent", params}
  end

  @doc """
  Cancels any active dragging in the page.
  """
  def cancel_dragging() do
    {"Input.cancelDragging", %{}}
  end

  @doc """
  Emulates touch event from the mouse event parameters.
  ## Parameters:
    - `type:string`: Type of the mouse event.
    - `x:integer`: X coordinate of the mouse pointer in DIP.
    - `y:integer`: Y coordinate of the mouse pointer in DIP.
    - `button:MouseButton`: Mouse button. Only "none", "left", "right" are supported.
    - `timestamp:TimeSinceEpoch`: (Optional) Time at which the event occurred (default: current time).
    - `deltaX:number`: (Optional) X delta in DIP for mouse wheel event (default: 0).
    - `deltaY:number`: (Optional) Y delta in DIP for mouse wheel event (default: 0).
    - `modifiers:integer`: (Optional) Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8
  (default: 0).
    - `clickCount:integer`: (Optional) Number of times the mouse button was clicked (default: 0).
  """
  def emulate_touch_from_mouse_event(
        type,
        x,
        y,
        button,
        timestamp \\ nil,
        delta_x \\ nil,
        delta_y \\ nil,
        modifiers \\ nil,
        click_count \\ nil
      ) do
    params =
      as_query([
        {"type", type},
        {"x", x},
        {"y", y},
        {"button", button},
        {"timestamp", timestamp},
        {"deltaX", delta_x},
        {"deltaY", delta_y},
        {"modifiers", modifiers},
        {"clickCount", click_count}
      ])

    {"Input.emulateTouchFromMouseEvent", params}
  end

  @doc """
  Ignores input events (useful while auditing page).
  ## Parameters:
    - `ignore:boolean`: Ignores input events processing when set to true.
  """
  def set_ignore_input_events(ignore) do
    params = as_query([{"ignore", ignore}])
    {"Input.setIgnoreInputEvents", params}
  end

  @doc """
  Prevents default drag and drop behavior and instead emits `Input.dragIntercepted` events.
  Drag and drop behavior can be directly controlled via `Input.dispatchDragEvent`.
  ## Parameters:
    - `enabled:boolean`: description not provided :(
  """
  def set_intercept_drags(enabled) do
    params = as_query([{"enabled", enabled}])
    {"Input.setInterceptDrags", params}
  end

  @doc """
  Synthesizes a pinch gesture over a time period by issuing appropriate touch events.
  ## Parameters:
    - `x:number`: X coordinate of the start of the gesture in CSS pixels.
    - `y:number`: Y coordinate of the start of the gesture in CSS pixels.
    - `scaleFactor:number`: Relative scale factor after zooming (>1.0 zooms in, <1.0 zooms out).
    - `relativeSpeed:integer`: (Optional) Relative pointer speed in pixels per second (default: 800).
    - `gestureSourceType:GestureSourceType`: (Optional) Which type of input events to be generated (default: 'default', which queries the platform
  for the preferred input type).
  """
  def synthesize_pinch_gesture(
        x,
        y,
        scale_factor,
        relative_speed \\ nil,
        gesture_source_type \\ nil
      ) do
    params =
      as_query([
        {"x", x},
        {"y", y},
        {"scaleFactor", scale_factor},
        {"relativeSpeed", relative_speed},
        {"gestureSourceType", gesture_source_type}
      ])

    {"Input.synthesizePinchGesture", params}
  end

  @doc """
  Synthesizes a scroll gesture over a time period by issuing appropriate touch events.
  ## Parameters:
    - `x:number`: X coordinate of the start of the gesture in CSS pixels.
    - `y:number`: Y coordinate of the start of the gesture in CSS pixels.
    - `xDistance:number`: (Optional) The distance to scroll along the X axis (positive to scroll left).
    - `yDistance:number`: (Optional) The distance to scroll along the Y axis (positive to scroll up).
    - `xOverscroll:number`: (Optional) The number of additional pixels to scroll back along the X axis, in addition to the given
  distance.
    - `yOverscroll:number`: (Optional) The number of additional pixels to scroll back along the Y axis, in addition to the given
  distance.
    - `preventFling:boolean`: (Optional) Prevent fling (default: true).
    - `speed:integer`: (Optional) Swipe speed in pixels per second (default: 800).
    - `gestureSourceType:GestureSourceType`: (Optional) Which type of input events to be generated (default: 'default', which queries the platform
  for the preferred input type).
    - `repeatCount:integer`: (Optional) The number of times to repeat the gesture (default: 0).
    - `repeatDelayMs:integer`: (Optional) The number of milliseconds delay between each repeat. (default: 250).
    - `interactionMarkerName:string`: (Optional) The name of the interaction markers to generate, if not empty (default: "").
  """
  def synthesize_scroll_gesture(
        x,
        y,
        x_distance \\ nil,
        y_distance \\ nil,
        x_overscroll \\ nil,
        y_overscroll \\ nil,
        prevent_fling \\ nil,
        speed \\ nil,
        gesture_source_type \\ nil,
        repeat_count \\ nil,
        repeat_delay_ms \\ nil,
        interaction_marker_name \\ nil
      ) do
    params =
      as_query([
        {"x", x},
        {"y", y},
        {"xDistance", x_distance},
        {"yDistance", y_distance},
        {"xOverscroll", x_overscroll},
        {"yOverscroll", y_overscroll},
        {"preventFling", prevent_fling},
        {"speed", speed},
        {"gestureSourceType", gesture_source_type},
        {"repeatCount", repeat_count},
        {"repeatDelayMs", repeat_delay_ms},
        {"interactionMarkerName", interaction_marker_name}
      ])

    {"Input.synthesizeScrollGesture", params}
  end

  @doc """
  Synthesizes a tap gesture over a time period by issuing appropriate touch events.
  ## Parameters:
    - `x:number`: X coordinate of the start of the gesture in CSS pixels.
    - `y:number`: Y coordinate of the start of the gesture in CSS pixels.
    - `duration:integer`: (Optional) Duration between touchdown and touchup events in ms (default: 50).
    - `tapCount:integer`: (Optional) Number of times to perform the tap (e.g. 2 for double tap, default: 1).
    - `gestureSourceType:GestureSourceType`: (Optional) Which type of input events to be generated (default: 'default', which queries the platform
  for the preferred input type).
  """
  def synthesize_tap_gesture(x, y, duration \\ nil, tap_count \\ nil, gesture_source_type \\ nil) do
    params =
      as_query([
        {"x", x},
        {"y", y},
        {"duration", duration},
        {"tapCount", tap_count},
        {"gestureSourceType", gesture_source_type}
      ])

    {"Input.synthesizeTapGesture", params}
  end
end
